### ISSUE TITLE
Loading Bert-large model results in OOM

### ISSUE THREAD

**Issue by ChaiBapchya** [huggingface/notebooks#37]
On a 2node p3dn.24xlarge instances, I find a OOM issue while trying to load a pre-trained `bert-large-uncased-whole-word-masking` model

Script
```
import tensorflow as tf
from transformers import TFAutoModelForSequenceClassification

model = TFAutoModelForSequenceClassification.from_pretrained('bert-large-uncased-whole-word-masking')
```

SM Launcher
```
import sagemaker
from sagemaker.huggingface import HuggingFace

role = sagemaker.get_execution_role()
distribution={'mpi': {'enabled':True,"custom_mpi_options":"-verbose --NCCL_DEBUG=INFO -x RDMAV_FORK_SAFE=1"}}

# instance configurations
instance_type='ml.p3dn.24xlarge'
instance_count=2

huggingface_estimator = HuggingFace(
    entry_point='model_load_hf_bert.py',
    source_dir='.',
    instance_type=instance_type,
    role=role,
    instance_count=instance_count,
    transformers_version='4.5.0',
    tensorflow_version='2.4.1',
    py_version='py37',
    distribution=distribution,
    debugger_hook_config=False, # currently needed
)
huggingface_estimator.fit()
```

| Nodes 	| Instance Type 	| Result 	|
|-------	|---------------	|--------	|
| 1     	| p3.2xlarge    	| success    	|
| 2     	| p3.2xlarge    	| success    	|
| 1     	| p3dn.24xlarge 	| OOM    	|
| 2     	| p3dn.24xlarge 	| OOM    	|

This issue is observed
- regardless of number of nodes

Specifically the line where it fails
https://github.com/huggingface/notebooks/blob/7a3bbdd26a154dd09db600df2e04bcb8325cab3f/sagemaker/07_tensorflow_distributed_training_data_parallelism/scripts/train.py#L125

For a detailed Stack Trace

```
[1,14]<stderr>:2021-05-04 22:39:11.526981: F ./tensorflow/core/kernels/random_op_gpu.h:232] Non-OK-status: GpuLaunchKernel(FillPhiloxRandomKernelLaunch<Distribution>, num_blocks, block_size, 0, d.stream(), gen, data, size, dist) status: Internal: out of memory
[1,15]<stderr>:2021-05-04 22:39:21.984104: W tensorflow/core/common_runtime/bfc_allocator.cc:431] Allocator (GPU_0_bfc) ran out of memory trying to allocate 119.23MiB (rounded to 125018112)requested by op TruncatedNormal

[1,15]<stderr>:Current allocation summary follows.
[1,15]<stderr>:2021-05-04 22:39:21.984204: W tensorflow/core/common_runtime/bfc_allocator.cc:439] *___________________________________________________________________________________________________
[1,15]<stderr>:2021-05-04 22:39:21.985568: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at random_op.cc:77 : Resource exhausted: OOM when allocating tensor with shape[30522,1024] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
[1,15]<stderr>:Traceback (most recent call last):
[1,15]<stderr>:  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
[1,15]<stderr>:    "__main__", mod_spec)
[1,15]<stderr>:  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
[1,15]<stderr>:    exec(code, run_globals)
[1,15]<stderr>:  File "/usr/local/lib/python3.7/site-packages/mpi4py/__main__.py", line 7, in <module>
[1,15]<stderr>:    main()
[1,15]<stderr>:  File "/usr/local/lib/python3.7/site-packages/mpi4py/run.py", line 196, in main
[1,15]<stderr>:    run_command_line(args)
[1,15]<stderr>:  File "/usr/local/lib/python3.7/site-packages/mpi4py/run.py", line 47, in run_command_line
[1,15]<stderr>:    run_path(sys.argv[0], run_name='__main__')
[1,15]<stderr>:  File "/usr/local/lib/python3.7/runpy.py", line 263, in run_path
[1,15]<stderr>:    pkg_name=pkg_name, script_name=fname)
[1,15]<stderr>:  File "/usr/local/lib/python3.7/runpy.py", line 96, in _run_module_code
[1,15]<stderr>:    mod_name, mod_spec, pkg_name, script_name)
[1,15]<stderr>:  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
[1,15]<stderr>:    exec(code, run_globals)
[1,15]<stderr>:  File "hf_bert_public.py", line 125, in <module>
[1,15]<stderr>:    model = TFAutoModelForSequenceClassification.from_pretrained(args.model_name)
[1,15]<stderr>:  File "/usr/local/lib/python3.7/site-packages/transformers/models/auto/auto_factory.py", line 360, in from_pretrained
[1,15]<stderr>:    pretrained_model_name_or_path, *model_args, config=config, **kwargs
[1,15]<stderr>:  File "/usr/local/lib/python3.7/site-packages/transformers/modeling_tf_utils.py", line 1271, in from_pretrained
[1,15]<stderr>:    model(model.dummy_inputs)  # build the network with dummy inputs
[1,15]<stderr>:  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 999, in __call__
[1,15]<stderr>:    outputs = call_fn(inputs, *args, **kwargs)
[1,15]<stderr>:  File "/usr/local/lib/python3.7/site-packages/transformers/models/bert/modeling_tf_bert.py", line 1450, in call
[1,15]<stderr>:    training=inputs["training"],
[1,15]<stderr>:  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 999, in __call__
[1,15]<stderr>:    outputs = call_fn(inputs, *args, **kwargs)
[1,15]<stderr>:  File "/usr/local/lib/python3.7/site-packages/transformers/models/bert/modeling_tf_bert.py", line 650, in call
[1,15]<stderr>:    training=inputs["training"],
[1,15]<stderr>:  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 996, in __call__
[1,15]<stderr>:    self._maybe_build(inputs)
[1,15]<stderr>:  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 2688, in _maybe_build
[1,15]<stderr>:    self.build(input_shapes)  # pylint:disable=not-callable
[1,15]<stderr>:  File "/usr/local/lib/python3.7/site-packages/transformers/models/bert/modeling_tf_bert.py", line 152, in build
[1,15]<stderr>:    initializer=get_initializer(self.initializer_range),
[1,15]<stderr>:  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 616, in add_weight
[1,15]<stderr>:    caching_device=caching_device)
[1,15]<stderr>:  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 750, in _add_variable_with_custom_getter
[1,15]<stderr>:    **kwargs_for_getter)
[1,15]<stderr>:  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer_utils.py", line 145, in make_variable
[1,15]<stderr>:    shape=variable_shape if variable_shape else None)
[1,15]<stderr>:  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 260, in __call__
[1,15]<stderr>:    return cls._variable_v1_call(*args, **kwargs)
[1,15]<stderr>:  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 221, in _variable_v1_call
[1,15]<stderr>:    shape=shape)
[1,15]<stderr>:  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 199, in <lambda>
[1,15]<stderr>:    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
[1,15]<stderr>:  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/ops/variable_scope.py", line 2597, in default_variable_creator
[1,15]<stderr>:    shape=shape)
[1,15]<stderr>:  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/ops/variables.py", line 264, in __call__
[1,15]<stderr>:    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
[1,15]<stderr>:  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1518, in __init__
[1,15]<stderr>:    distribute_strategy=distribute_strategy)
[1,15]<stderr>:  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1651, in _init_from_args
[1,15]<stderr>:    initial_value() if init_from_fn else initial_value,
[1,15]<stderr>:  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/initializers/initializers_v2.py", line 342, in __call__
[1,15]<stderr>:    return super(TruncatedNormal, self).__call__(shape, dtype=_get_dtype(dtype))
[1,15]<stderr>:  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/ops/init_ops_v2.py", line 450, in __call__
[1,15]<stderr>:    self.stddev, dtype)
[1,15]<stderr>:  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/ops/init_ops_v2.py", line 1053, in truncated_normal
[1,15]<stderr>:    shape=shape, mean=mean, stddev=stddev, dtype=dtype, seed=self.seed)
[1,15]<stderr>:  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
[1,15]<stderr>:    return target(*args, **kwargs)
[1,15]<stderr>:  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/ops/random_ops.py", line 196, in truncated_normal
[1,15]<stderr>:    shape_tensor, dtype, seed=seed1, seed2=seed2)
[1,15]<stderr>:  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/ops/gen_random_ops.py", line 902, in truncated_normal
[1,15]<stderr>:    _ops.raise_from_not_ok_status(e, name)
[1,15]<stderr>:  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 6843, in raise_from_not_ok_status
[1,15]<stderr>:    six.raise_from(core._status_to_exception(e.code, message), None)
[1,15]<stderr>:  File "<string>", line 3, in raise_from
[1,15]<stderr>:tensorflow.python.framework.errors_impl.ResourceExhaustedError[1,15]<stderr>:: OOM when allocating tensor with shape[30522,1024] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:TruncatedNormal]
```

**Comment by ChaiBapchya** [comment]
Issue is with the number of gpus per node that are visible
- p3.2xlarge has 1gpu(s)/node
- p3dn.24xlarge has 8gpu(s)/node

```
import tensorflow as tf
from transformers import TFAutoModelForSequenceClassification
import horovod.tensorflow.keras as hvd
# initial distributed training
hvd.init()

# Pin GPU to be used to process local rank (one GPU per process)
gpus = tf.config.experimental.list_physical_devices("GPU")
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)
if gpus:
    tf.config.experimental.set_visible_devices(gpus[hvd.local_rank()], "GPU")
model = TFAutoModelForSequenceClassification.from_pretrained('bert-large-uncased-whole-word-masking')
```
This works as expected.
